MYSQL_USERNAME: ${MYSQL_USERNAME:root}
MYSQL_PASSWORD: ${MYSQL_PASSWORD:password}
MYSQL_HOST: ${MYSQL_HOST:127.0.0.1}
MYSQL_PORT: ${MYSQL_PORT:3306}
MYSQL_DATABASE: ${MYSQL_DATABASE:db2}

CONTAINER_PORT: ${CONTAINER_PORT:8080}
SPRING_ACTIVE_PROFILES: dev

MAIL_USERNAME: ${MAIL_USERNAME:}
MAIL_PASSWORD: ${MAIL_PASSWORD:}
VERIFY_EMAIL_HOST: ${VERIFY_EMAIL_HOST:http://localhost:8080}
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587

UI_APP_URL: ${UI_APP_URL:http://localhost:4200}

JWT_SECRET: ${JWT_SECRET:devOnlySecretKeyDoNotUseInProductionMustBeLongEnough1}
