# psql config - wasn't working unless I ran the psqlschema.sql file inside of pgadmin4 within the database noted on line 5. We will use the tutorial's mysql config instead, and possibly route back to this
#spring:
#  datasource:
#    # Replace 'serverdb' with the name of your actual PostgreSQL database
#    url: jdbc:postgresql://localhost:5432/db1
#    # Replace with your PostgreSQL username (default is often 'postgres')
#    username: postgres
#    # Replace it with your PostgreSQL password
#    password: password
#  jpa:
#    show-sql: true
#    hibernate:
#      # 'update' will automatically create or update your database tables based on your Server entity
#      ddl-auto: update
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
#        # Tells Hibernate to use the PostgreSQL dialect - this is also deprecated so it is not needed
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
# Tells Hibernate to use the PostgreSQL dialect - this is also deprecated so it is not needed
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
#  sql:
#    init:
#      mode: always
##      continue-on-error: false

# This is the MySQL config, following the tutorial.
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/db2
#    username: root
#    password: password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
#        format_sql: true
#    generate-ddl: true
#  sql:
#    init:
#      mode: never
#      continue-on-error: false
#logging:
#  level:
#    org.springframework.boot: DEBUG
#    org.hibernate: DEBUG
#debug: true


# here we can just define what profile we want to use - either application-dev, prod, etc and Spring Boot will know which profile to use!
spring:
  profiles:
    active: @spring.profiles.active@
application:
  title: Spring Boot Angular Full Stack Application
  version: v1.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.hibernate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
