# This is the MySQL config, following the tutorial.
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db2
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    generate-ddl: true
  sql:
    init:
      mode: never
      continue-on-error: true
logging:
  level:
    "[org.springframework.security, org.springframework.boot, org.hibernate]": DEBUG
    