package com.bob.angularspringbootfullstack.utils;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

/**
 * Decides whether a rejected request came from a browser <em>navigation</em> rather than the SPA's
 * XHR layer, and renders a branded HTML error page for the former.
 * <p>
 * <strong>The problem this solves.</strong>
 * {@link com.bob.angularspringbootfullstack.handler.CustomAuthenticationEntryPoint} and
 * {@link com.bob.angularspringbootfullstack.handler.CustomAccessDeniedHandler} both answer with the
 * {@code HttpResponse} JSON envelope. That is exactly right for the Angular client — the token
 * interceptor's silent-refresh path keys off a clean {@code 401}, and a redirect or an HTML body
 * would break it (see the {@code defaultAuthenticationEntryPointFor} note in {@code SecurityConfig}).
 * It is exactly wrong for a human who typed a protected URL into the address bar, or followed a
 * stale link from an email: once Angular is served from the same origin as the API in Docker/prod,
 * that person is shown a wall of raw JSON.
 * <p>
 * <strong>Why {@code Accept} alone is not the signal.</strong> The obvious content-negotiation
 * check — "does {@code Accept} contain {@code text/html}?" — is unreliable here, because Angular's
 * {@code HttpClient} does not set an {@code Accept} header of its own, so an XHR can arrive with no
 * header at all or with a browser-supplied default. Getting that wrong means serving HTML to the
 * interceptor and silently disabling token refresh. The primary signal used instead is the
 * {@code Sec-Fetch-Mode} fetch-metadata header, which browsers set to {@code navigate} for top-level
 * navigations and to {@code cors}/{@code same-origin} for {@code fetch}/XHR — it is generated by the
 * browser, not by application code, so a script cannot forge it.
 * <p>
 * The rendered page carries no external references (no CDN font, no image, no script), which keeps
 * it compatible with the strict Content-Security-Policy declared in {@code SecurityConfig}:
 * {@code default-src 'self'} with inline styles permitted but inline scripts allow-listed by hash.
 *
 * @see com.bob.angularspringbootfullstack.handler.CustomAuthenticationEntryPoint
 * @see com.bob.angularspringbootfullstack.handler.CustomAccessDeniedHandler
 */
public final class BrowserErrorPage {

    /** Static-only utility. */
    private BrowserErrorPage() {
    }

    /**
     * Reports whether this request is a top-level browser navigation, and therefore whether the
     * caller should answer with an HTML page instead of the JSON envelope.
     * <p>
     * The checks run in order of trustworthiness:
     * <ol>
     *   <li>An explicit {@code X-Requested-With: XMLHttpRequest} is a definitive "this is a
     *       programmatic call" and short-circuits to JSON.</li>
     *   <li>If any fetch-metadata header is present, it is authoritative: HTML only for
     *       {@code Sec-Fetch-Mode: navigate} targeting a {@code document}. Every modern browser
     *       sends these on same-origin requests, so this is the branch that runs in practice.</li>
     *   <li>Otherwise (an older client, or a bare {@code curl}), fall back to a conservative
     *       heuristic: only a {@code GET} that explicitly asks for {@code text/html} and carries no
     *       {@code Authorization} header is treated as a navigation. Requiring the absence of a
     *       bearer token matters because a navigation cannot carry one — only the SPA's interceptor
     *       attaches it.</li>
     * </ol>
     * The bias throughout is toward JSON: a false negative degrades a human's error page, while a
     * false positive would break automatic token refresh for every user.
     *
     * @param request the rejected request
     * @return {@code true} if an HTML page is the appropriate response
     */
    public static boolean isBrowserNavigation(HttpServletRequest request) {
        if ("XMLHttpRequest".equalsIgnoreCase(request.getHeader("X-Requested-With"))) {
            return false;
        }

        String mode = request.getHeader("Sec-Fetch-Mode");
        String dest = request.getHeader("Sec-Fetch-Dest");
        if (mode != null || dest != null) {
            return "navigate".equalsIgnoreCase(mode)
                    && (dest == null || "document".equalsIgnoreCase(dest));
        }

        String accept = request.getHeader("Accept");
        return "GET".equalsIgnoreCase(request.getMethod())
                && accept != null
                && accept.contains("text/html")
                && request.getHeader("Authorization") == null;
    }

    /**
     * Writes a branded, self-contained HTML error page and commits the response.
     * <p>
     * The status code is preserved exactly as the security handler intended — this changes the
     * <em>representation</em> of a 401/403, never its meaning. Styling mirrors the SPA's dark theme
     * from {@code styles.css} and honours {@code prefers-color-scheme}: the app's own theme toggle
     * stores its choice in {@code localStorage}, which this page cannot read without an inline
     * script the CSP would reject, so the OS-level preference is the closest honest approximation.
     *
     * @param response  the servlet response to write to
     * @param status    the HTTP status to send (401 or 403)
     * @param eyebrow   small uppercase label above the heading, e.g. {@code "401 · Unauthorized"}
     * @param heading   the page headline
     * @param message   the explanatory sentence — the same user-facing text the JSON envelope carries
     * @param ctaHref   destination of the primary action button, an SPA route such as {@code /login}
     * @param ctaLabel  label of the primary action button
     * @throws IOException if writing to the response fails
     */
    public static void write(HttpServletResponse response, int status, String eyebrow, String heading,
                             String message, String ctaHref, String ctaLabel) throws IOException {
        response.setStatus(status);
        response.setContentType("text/html;charset=UTF-8");
        response.setCharacterEncoding(StandardCharsets.UTF_8.name());
        response.getWriter().write(render(eyebrow, heading, message, ctaHref, ctaLabel));
        response.getWriter().flush();
    }

    /**
     * Builds the page markup.
     * <p>
     * Kept in one string rather than a template file because the project ships no template engine
     * (see {@link EmailTemplate} for the same reasoning) and because an error page that depends on
     * view resolution can fail for the very reasons it is being rendered.
     *
     * @param eyebrow  small uppercase label
     * @param heading  the headline
     * @param message  the explanatory sentence
     * @param ctaHref  primary action destination
     * @param ctaLabel primary action label
     * @return a complete HTML document
     */
    private static String render(String eyebrow, String heading, String message,
                                 String ctaHref, String ctaLabel) {
        return """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width,initial-scale=1">
                <meta name="color-scheme" content="dark light">
                <title>%s — TesseraApp</title>
                <style>
                  :root {
                    --bg: #0a0c12;
                    --card: #12161f;
                    --border: rgba(255,255,255,0.08);
                    --text-strong: #f3f5f9;
                    --text: #c3cad9;
                    --muted: #8a93a6;
                    --faint: #5b6477;
                    --accent: #6b5bff;
                    --accent-soft: #8674ff;
                    --aurora: rgba(107,91,255,0.16);
                  }
                  @media (prefers-color-scheme: light) {
                    :root {
                      --bg: #f5f6fb;
                      --card: #ffffff;
                      --border: rgba(15,19,28,0.10);
                      --text-strong: #0f131c;
                      --text: #3a4252;
                      --muted: #6b7385;
                      --faint: #9aa1b2;
                      --accent: #5a48f0;
                      --accent-soft: #4836d6;
                      --aurora: rgba(90,72,240,0.10);
                    }
                  }
                  * { box-sizing: border-box; }
                  body {
                    margin: 0;
                    min-height: 100vh;
                    display: grid;
                    place-items: center;
                    padding: 24px;
                    background:
                      radial-gradient(60rem 40rem at 50%% -10%%, var(--aurora), transparent 70%%),
                      var(--bg);
                    color: var(--text);
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                                 'Helvetica Neue', Arial, sans-serif;
                    -webkit-font-smoothing: antialiased;
                  }
                  .wrap { width: 100%%; max-width: 460px; }
                  .brand {
                    font-size: 17px; font-weight: 700; letter-spacing: -0.01em;
                    color: var(--text-strong); margin: 0 0 18px 4px;
                  }
                  .brand span { color: var(--accent-soft); }
                  .card {
                    background: var(--card);
                    border: 1px solid var(--border);
                    border-radius: 16px;
                    padding: 34px 30px;
                    box-shadow: 0 18px 50px rgba(0,0,0,0.28);
                  }
                  .eyebrow {
                    margin: 0 0 10px;
                    font-size: 11px; font-weight: 600;
                    letter-spacing: 0.14em; text-transform: uppercase;
                    color: var(--accent-soft);
                  }
                  h1 {
                    margin: 0 0 14px;
                    font-size: 23px; line-height: 1.3; font-weight: 600;
                    color: var(--text-strong);
                  }
                  p { margin: 0 0 22px; font-size: 15px; line-height: 1.65; }
                  .cta {
                    display: inline-block;
                    padding: 12px 26px;
                    border-radius: 999px;
                    background: var(--accent);
                    color: #fff;
                    font-size: 15px; font-weight: 600;
                    text-decoration: none;
                  }
                  .cta:hover { background: var(--accent-soft); }
                  .foot {
                    margin: 18px 4px 0;
                    font-size: 12px; line-height: 1.6; color: var(--faint);
                  }
                </style>
                </head>
                <body>
                  <div class="wrap">
                    <div class="brand">Tessera<span>App</span></div>
                    <main class="card">
                      <p class="eyebrow">%s</p>
                      <h1>%s</h1>
                      <p>%s</p>
                      <a class="cta" href="%s">%s</a>
                    </main>
                    <p class="foot">If you reached this from a link, it may have expired or been intended for a different account.</p>
                  </div>
                </body>
                </html>
                """.formatted(escape(heading), escape(eyebrow), escape(heading), escape(message),
                escape(ctaHref), escape(ctaLabel));
    }

    /**
     * Escapes XML-significant characters so message text cannot break out of the surrounding markup.
     * <p>
     * Relevant because the 403 message is derived from the request path via
     * {@code CapabilityCatalog.actionKeyFor(request)} and a {@code MessageSource} lookup in
     * {@code CustomAccessDeniedHandler} — attacker-influenced input reaching a rendered page is
     * precisely the reflected-XSS shape, and this is the one place it could land.
     *
     * @param value raw text, possibly {@code null}
     * @return escaped text, or an empty string when {@code value} is {@code null}
     */
    private static String escape(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
