package com.bob.angularspringbootfullstack.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.validation.constraints.NotEmpty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_DEFAULT;

/**
 * Role entity representing a user role/authority in the system.
 *
 * <p>This model maps to the {@code roles} table and provides the permission string that is
 * converted into Spring Security {@code GrantedAuthority} instances.
 */
@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(NON_DEFAULT)
/**
 * Role entity representing a user role/authority in the system.
 *
 * This class maps directly to the 'roles' table in the database and defines
 * role information used for authorization and access control. Roles are assigned
 * to users through the user_roles junction table (many-to-many relationship).
 *
 * Fields:
 * - id: Unique identifier for the role (auto-generated by database)
 * - name: Role name (required, non-empty) - e.g., "ROLE_USER", "ROLE_ADMIN"
 * - permission: Permission string or code associated with this role - used to grant specific privileges
 */
public class Role {
    private Long id;
    @NotEmpty(message = "Role name is required")
    private String name;
    private String permission;
}
