package com.bob.angularspringbootfullstack.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_DEFAULT;

@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(NON_DEFAULT)
/**
 * User entity representing a registered user in the system.
 *
 * This class maps directly to the 'users' table in the database and contains
 * all user profile and authentication information. It uses Lombok annotations
 * for boilerplate code generation and Spring validation annotations for input validation.
 *
 * Fields:
 * - id: Unique identifier for the user (auto-generated by database)
 * - firstName: User's first name (required, non-empty)
 * - lastName: User's last name (required, non-empty)
 * - email: User's email address (required, must be valid email format)
 * - password: Encrypted user password (required, non-empty)
 * - imageUrl: URL to user's profile picture
 * - address: User's physical address
 * - phoneNumber: User's phone number for 2FA
 * - bio: User's biography/description
 * - title: User's professional title or designation
 * - enabled: Flag indicating if user account is enabled
 * - isNotLocked: Flag indicating if user account is locked (security feature)
 * - isUsing2FA: Flag indicating if user has 2-factor authentication enabled
 * - createdAt: Timestamp of account creation
 */
public class User {
    private Long id;
    @NotEmpty(message = "First name is required")
    private String firstName;
    @NotEmpty(message = "Last name is required")
    private String lastName;
    @Email(message = "Email is required")
    private String email;
    @NotEmpty(message = "Password is required")
    private String password;
    private String imageUrl;
    private String address;
    private String phoneNumber;
    private String bio;
    private String title;
    private boolean enabled;
    private boolean isNotLocked;
    private boolean isUsing2FA;
    private LocalDateTime createdAt;
}
