spring:
  datasource:
    # Replace 'serverdb' with the name of your actual PostgreSQL database
    url: jdbc:postgresql://localhost:5432/capitadb
    # Replace with your PostgreSQL username (default is often 'postgres')
    username: postgres
    # Replace it with your PostgreSQL password
    password: password
  jpa:
    show-sql: true
    hibernate:
      # 'update' will automatically create or update your database tables based on your Server entity
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        # Tells Hibernate to use the PostgreSQL dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true